from mock import MagicMock, patch
from payg_loan_system.transaction_requests.nonpayg_device_picker import (
    should_force_auto_generated_nonpayg,
    should_show_auto_generated_nonpayg,
)
from constants import NON_PAYG_TYPE


def _offer(device_type=None, product_sub_type=None):
    return MagicMock(device_type=device_type, product_sub_type=product_sub_type)


def _addon_offer(product_type=None, product_sub_type=None):
    return MagicMock(product_type=product_type, product_sub_type=product_sub_type)


class TestShouldShowAutoGeneratedNonpayg:

    @patch('payg_loan_system.transaction_requests.nonpayg_device_picker.SettingsService.get_setting', return_value=False)
    def test_hidden_when_npg_setting_disabled(self, _setting):
        assert should_show_auto_generated_nonpayg() is False
        assert should_show_auto_generated_nonpayg(offer=_offer(device_type=NON_PAYG_TYPE)) is False

    @patch('payg_loan_system.transaction_requests.nonpayg_device_picker.SettingsService.get_setting', return_value=True)
    def test_shown_when_no_offer(self, _setting):
        assert should_show_auto_generated_nonpayg() is True

    @patch('payg_loan_system.transaction_requests.nonpayg_device_picker.SettingsService.get_setting', return_value=True)
    def test_shown_for_unrestricted_offer(self, _setting):
        assert should_show_auto_generated_nonpayg(offer=_offer()) is True

    @patch('payg_loan_system.transaction_requests.nonpayg_device_picker.SettingsService.get_setting', return_value=True)
    def test_shown_for_npg_offer_without_subtype(self, _setting):
        assert should_show_auto_generated_nonpayg(offer=_offer(device_type=NON_PAYG_TYPE)) is True

    @patch('payg_loan_system.transaction_requests.nonpayg_device_picker.SettingsService.get_setting', return_value=True)
    def test_hidden_for_npg_offer_with_subtype(self, _setting):
        assert should_show_auto_generated_nonpayg(
            offer=_offer(device_type=NON_PAYG_TYPE, product_sub_type=object())
        ) is False

    @patch('payg_loan_system.transaction_requests.nonpayg_device_picker.SettingsService.get_setting', return_value=True)
    def test_hidden_for_payg_device_type(self, _setting):
        assert should_show_auto_generated_nonpayg(offer=_offer(device_type='ANGAZA')) is False

    @patch('payg_loan_system.transaction_requests.nonpayg_device_picker.SettingsService.get_setting', return_value=True)
    def test_hidden_for_addon_with_product_type(self, _setting):
        assert should_show_auto_generated_nonpayg(
            addon_offer=_addon_offer(product_type=NON_PAYG_TYPE)
        ) is False

    @patch('payg_loan_system.transaction_requests.nonpayg_device_picker.SettingsService.get_setting', return_value=True)
    def test_hidden_for_addon_with_subtype_only(self, _setting):
        assert should_show_auto_generated_nonpayg(
            addon_offer=_addon_offer(product_sub_type=object())
        ) is False

    @patch('payg_loan_system.transaction_requests.nonpayg_device_picker.SettingsService.get_setting', return_value=True)
    def test_shown_for_addon_without_type_or_subtype(self, _setting):
        assert should_show_auto_generated_nonpayg(addon_offer=_addon_offer()) is True


class TestShouldForceAutoGeneratedNonpayg:

    def test_forced_for_npg_without_subtype(self):
        assert should_force_auto_generated_nonpayg(_offer(device_type=NON_PAYG_TYPE)) is True

    def test_not_forced_for_npg_with_subtype(self):
        assert should_force_auto_generated_nonpayg(
            _offer(device_type=NON_PAYG_TYPE, product_sub_type=object())
        ) is False

    def test_not_forced_without_offer(self):
        assert should_force_auto_generated_nonpayg(None) is False

    def test_not_forced_for_payg_type(self):
        assert should_force_auto_generated_nonpayg(_offer(device_type='ANGAZA')) is False
