from datetime import datetime, timedelta
from urllib.parse import parse_qs, urlparse
from core_system.operational_entities.services.client_group_getter_service import ClientGroupGetterService
from core_system.portfolios.services.portfolio_getter_service import PortfolioGetterService
from core_system.operational_entities.services.operational_entities_getter import OperationalEntitiesGetterService
from payg_loan_system.contracts.services.addons.addon_offer_getter_service import AddonOfferGetterService
from payg_loan_system.devices.device_list_service import DeviceListService
from shared.helpers.clock import Clock
from shared.helpers.form_helpers import dateTimePickerToStandard
from flask_login import login_required, current_user
from flask import request, redirect, url_for, flash, render_template

from pony.orm import db_session
from payg_loan_system.contracts.models.addons_model import AddOnLoanExtensionMode, AddOnType, ContractAddOn
from payg_loan_system.contracts.services.addon_list_service import AddonListService
from payg_loan_system.contracts.services.addon_sorter import AddonSorter
from shared.helpers.authorizer import authorizer
from shared.helpers.pagination import Pagination
from config import ADDONS_STATUSES_NAMES
from shared.helpers.select2 import render
from shared.services.settings_service import SettingsService
from . import contract


@contract.route('/addons', methods=['GET', 'POST'])
@login_required
@authorizer(['ViewLeads', 'ViewClients'])
@db_session
def list_addons():

    active_tab = request.args.get('tab', 'pending')
    search = request.form.get('search', request.args.get('search', ''))
    entity = OperationalEntitiesGetterService.extract_from_user_and_id(current_user, request.args, "entity_id", strict=False)
    portfolio = PortfolioGetterService.extract_from_user_and_id(current_user, request.args, "portfolio_id", strict=False)
    client_group = ClientGroupGetterService.extract_from_user_and_id(current_user, request.args, "client_group_id", strict=False)
    view = request.args.get('view', 'all')

    offer_type = request.args.get('offer_type', None)
    offer_id = request.args.get('offer_id', None)

    default_from = (datetime.now() - timedelta(days=365*10)).strftime("%Y-%m-%d")
    from_date_str = request.args.get('from_date', default_from)
    to_date_str = request.args.get('to_date', (datetime.now() + timedelta(days=1)).strftime("%Y-%m-%d"))
    from_date = dateTimePickerToStandard(from_date_str)
    from_date_utc = Clock.localize_to_utc(from_date)
    to_date = dateTimePickerToStandard(to_date_str, '23:59')
    to_date_utc = Clock.localize_to_utc(to_date)

    paginations = {}

    if not SettingsService.get_setting('FeatureToggles').get('OffTaking'):
        ADDONS_STATUSES_NAMES.pop('offtaking', None)
    
    for tab in ADDONS_STATUSES_NAMES:
        paginations[tab] = Pagination.generate(request, tab=tab)
        addons = AddonListService.get_from_filtered_view(
            current_user.reload(),
            view=view,
            entity=entity,
            client_group=client_group,
            portfolio=portfolio,
            search=search,
            status=tab,
            offer_type=offer_type,
            offer_id=offer_id,
            from_date=from_date_utc,
            to_date=to_date_utc
        )
        addons = addons.filter(lambda a: a.not_lead)
        paginations[tab].objects = AddonSorter.sort(addons, paginations[tab].sort, 'id')

    

    devices = DeviceListService.get_non_used_devices_for_user_list(current_user)
    select2 = {
            'devices':{
                'items': devices,
                'id': 'composed_serial',
                'text': 'composed_serial',
                'force_ajax': True 
            }
        }
    if 'source' in request.args and request.args['source'] in select2:
        # Parse the URL
        parsed_url = urlparse(request.args['ajax-Url'])
        # Extract query parameters as a dictionary
        query_params = parse_qs(parsed_url.query)
        reference = query_params.get('contract_addon_reference', [None])[0]
        contract_addon=AddonListService.get_from_user_and_properties(current_user, reference=reference)
        devices = DeviceListService.get_non_used_devices_for_user_list(current_user, add_on_offer=contract_addon.offer_version.offer)
        select2 = {
            'devices':{
                'items': devices,
                'id': 'composed_serial',
                'text': 'composed_serial',
                'force_ajax': True 
            }
        }
        return render(None, select2=select2)
    return render(
        'list_addons.html',
        view=view,
        views={
            'all': ('all_out', 'View all'),
            'managed_by_me': ('assignment', 'Managed by me'),
            'generated_by_me': ('gps_fixed', 'Generated by me')
        },
        entity=entity,
        portfolio=portfolio,
        client_group=client_group,
        active_tab=active_tab,
        paginations=paginations,
        tabs=ADDONS_STATUSES_NAMES,
        search=search,
        AddOnType=AddOnType,
        AddOnLoanExtensionMode=AddOnLoanExtensionMode,
        offer_types=[(t,t) for t in AddOnType.to_list()],
        offer_type=offer_type,
        addon_offers={o.id:o.name for o in AddonOfferGetterService.get_list(current_user)},
        offer_id=offer_id,
        from_date=from_date,
        to_date=to_date,
        select2=select2
    )


@contract.route('addons/<addon_reference>', methods=['GET', 'POST'])
@login_required
@authorizer('ViewAddOns')
@db_session
def view_addon(addon_reference):
    addon = AddonListService.get_filtered_objects(current_user, addon_reference=addon_reference).first()
    if not addon:
        flash('This addon does not exist. ')
        return redirect(url_for('.list_addons'))
    return render_template('view_addon.html', addon=addon, AddOnType=AddOnType, AddOnLoanExtensionMode=AddOnLoanExtensionMode)