from payg_loan_system.transaction_requests.services.default_service import DefaultTransactionService
from payg_loan_system.transaction_requests.api_views.transaction_resource import TransactionResource


class DefaultTransactionResource(TransactionResource):

    service = DefaultTransactionService
