from payg_loan_system.transaction_requests.services.undo_default_service import UndoDefaultTransactionService
from payg_loan_system.transaction_requests.api_views.transaction_resource import TransactionResource


class UndoDefaultTransactionResource(TransactionResource):

    service = UndoDefaultTransactionService
