from collections import OrderedDict

LevelNames = {1: 'SuperAdmin',
              2: 'Admin',
              3: 'Manager',
              4: 'Mentor',
              5: 'Retailer',
              6: 'SuperGuest',
              7: 'Guest',
              8: 'LeadGenerator',
              9: 'ViewOnly',
              10: 'Accountant',
              11: 'SuperManager',
              12: 'Accountant'}

permission_themes = {
    'Tasks': ['Tasks'],
    'Sales': ['Leads', 'LeadGenerators'],
    'Clients': ['Clients', 'AddOns', 'Actions'],
    'After-Sales': ['Issues', 'Interactions', 'Planning'],
    'Management': ['Users', 'Villages', 'Clusters', 'Hubs', 'Zones', 'Regions', 'ClientGroups', 'Roles', 'Portfolios'],
    'Accounting': ['Payments', 'ReversedPayments', 'Expenses', 'Transfers', 'Accounts'],
    'Inventory': ['Devices', 'ViewStock', 'MoveStock'],
    'General': ['Mobile', 'Dashboards', 'Messages', 'PhoneNumbers'],
    'Admin': ['Admin', 'Logs', 'APIHook', 'Offers', 'AddonOffers', 'Forms', 'APIDocumentation', 'UserJourney'],
}

theme_icons = {
    'Tasks': 'tasks',
    'Sales': 'sales',
    'Clients': 'client',
    'After-Sales': 'service',
    'Management': 'management',
    'Accounting': 'accounting',
    'Inventory': 'inventory',
    'General': 'permission',
    'Admin': 'admin',
}

permission_themes = OrderedDict(permission_themes.items())


all_permissions = {
    # Contracts
    'Clients': ['View', 'Edit', 'EditPortfolio', 'FillCustomForms', 'AddTags',
                'CreateTags', 'Merge'],
    'AddOns': ['Approve', 'Cancel', 'AddToContract', 'AddContractTermsChange',
               'MarkAsDelivered', 'MarkAsUnDelivered', 'MarkAsDeliveredWithoutPlannedDate',
               'EditPlannedDeliveryDate', 'AddPurchasing'],
    'Actions': ['View', 'SyncActivation', 'MakeOnStockOutsideView', 'DoChangeOffer',
                'DeRegister', 'GiveDiscount', 'GiveDiscountOver2Days',
                'Register', 'CollectCash', 'PayClient', 'SwapDevice', 'GiveDelay',
                'GiveDelayOver2Days', 'GiveNegativeDiscountToCompleted', 'MarkContractDefaulted',
                'UndoContractDefaulted', 'GiveTokensOffline', 'ChangeExpectedPaid',
                'CancelContract', 'ViewCustomButton', 'PauseContract', 'ResumeContract'],
    # Sales
    'Leads': ['View', 'ViewCreated', 'ViewBadge', 'Add', 'Edit', 'EditPortfolio',
              'EditInstalled', 'Approve', 'SetCommission', 'EditPlannedDeliveryDate',
              'OverrideDeliveryDateLimits', 'EditOfferPartiallyPaid', 'EditOfferAwaitingDelivery',
              'FillCustomForms', 'EditAllocatedDevice', 'MoveToRestrictedStatus',
              'EditRestrictedPersonalDetails'],
    'LeadGenerators': ['ViewOwn', 'View', 'Add', 'Merge', 'Edit', 'GiveCommissionTo'],
    # AfterSales
    'Issues': ['View', 'Add', 'Edit', 'ViewBadge', 'AddNotes', 'DeleteNotes', 'DeleteOwnNotes'],
    'Interactions': ['View', 'Add', 'Edit', 'Delete'],
    'Planning': ['View', 'Add', 'Edit', 'Delete'],
    # Accounting
    'Payments': ['View', 'ViewOrphaned', 'Add', 'AdjustBalanceAndReconcile', 'EditWallet',
                 'ViewOdyssey'],
    'ReversedPayments': ['View', 'Add', 'Handle'],
    'Accounts': ['View', 'Edit', 'ManageAll', 'DownloadGlobal', 'Manage'],
    'Transfers': ['EditMade', 'Request', 'Approve', 'Confirm', 'View', 'Delete',
                  'ViewBadge'],
    'Expenses': ['View', 'Add', 'Edit', 'EditOwn', 'EditOthers', 'EditAmount', 'Delete'],
    # Management
    'Villages': ['Add', 'Edit', 'Delete'],
    'Clusters': ['Add', 'Edit', 'Delete'],
    'Hubs': ['Add', 'Edit', 'Delete'],
    'Zones': ['Add', 'Edit', 'Delete'],
    'Regions': ['Add', 'Edit', 'Delete'],
    'ClientGroups': ['Add', 'Edit', 'Delete'],
    'Users': ['View', 'ViewOwn', 'Edit', 'Add'],
    'Roles': ['View', 'Create', 'Assign'],
    # Logistics
    'Devices': ['Add', 'EditSubType', 'Delete', 'ChangePAYGMode', 'ForcePAYGMode',
                'AddNotes', 'DeleteNotes', 'CreateTags', 'EditTags', 'ViewPaygo', 'Pair'],
    'ViewStock': ['InStock', 'WithUsers', 'WithMe', 'WithClients', 'Orphaned', 'ManageQuantity'],
    'MoveStock': ['FromOrphaned', 'FromInStock', 'FromUsers', 'FromWithMe', 'FromLost',
                  'ToOrphaned', 'ToInStock', 'ToUsers', 'ToWithMe', 'ToLost',
                  'Add', 'Delete'],
    # Admin
    'Admin': ['ViewSettingsInterface', 'CreateAPIToken', 'ViewActivityLog', 'ExportData',
              'ConfigurePaymentRouter', 'ConfigureAutomatedMessages', 'ConfigureSalesManagement',
              'ConfigurePaymentManagement', 'ConfigureLocalSettings', 'ConfigureProduct',
              'ConfigureGeneralSettings', 'ConfigurePersonalInfo', 'ConfigureOperationalEntities',
              'ConfigureLanguageSettings', 'ConfigureDeviceAPI', 'ConfigureMobileAppSettings',
              'ConfigureSpecialSettings', 'EditCustomSMS', 'CustomizePlatform', 'EditBanner',
              'SeeAllNotifications', 'SeeHubNotifications', 'ViewBilling', 'APICaller', 'ConfigureTaskType', 'ConfigurePackageInstaller', 'ConfigureAutomations'],
    'Offers': ['View', 'Add', 'Edit', 'ViewLumpSum', 'ViewLoan', 'EditLoan', 'AddLoan'],
    'AddonOffers': ['View', 'Add', 'Edit'],
    'Logs': ['View', 'ViewFaults'],
    'Messages': ['ViewAll', 'View', 'ViewOrphaned', 'AddOutgoing', 'AddIncoming', 'Add'],
    'APIHook': ['Add', 'Delete'],
    'Forms': ['View', 'Add', 'Edit', 'Delete', 'EditInteractionsSettings',
              'EditClientLeadDataSettings', 'AnswerProtectedQuestion'],
    'APIDocumentation' : ['View'],
    'UserJourney': ['Run', 'List', 'Add', 'Edit', 'FillCustomForms'],
    # General
    'Dashboards': ['View', 'ViewGlobal', 'Gogla'],
    'PhoneNumbers': ['Delete', 'ViewOrphaned', 'RemoveLast'],
    'Portfolios': ['List', 'View', 'Edit', 'Delete', 'Create'],
    'Mobile': ['SyncLeads', 'SyncAllCreatedLeads', 'SyncAllGeneratedLeads',
            'SyncInstalledLast2WeeksLeads', 'SyncInstalledLast2MonthsLeads',
            'SyncInstalledLast12MonthsLeads', 'SyncOwnLeadGenerator', 'SyncLeadGenerators',
            'SyncClients', 'SyncAllCreatedClients', 'SyncAllGeneratedClients',
            'SyncCompletedClients', 'SyncInteractions', 'SyncPlanning', 'SyncTaskAssignedToMe'],
    'Tasks': ['View', 'Add', 'Edit', 'Delete', 
             'ViewAssigned', 'ChangeStatusOfAssigned', 'AddAssigned', 'EditCreated', 'DeleteCreated'],
    'Automations': ['View', 'Edit']
}

def all_permissions_in_group(group):
    return [p+group for p in all_permissions[group]]

global_permissions = [
    'SuperAdmin',
    'MergeClients', 'CreateTagsClients', 
    'SyncAllCreatedLeadsMobile', 'SyncAllGeneratedLeadsMobile', 'SyncAllCreatedClientsMobile',
    'SyncLeadGeneratorsMobile', 'SyncOwnLeadGeneratorMobile',
    'SyncAllGeneratedClientsMobile', 'ViewOrphanedPhoneNumbers', 'ViewDashboards',
    'ViewGlobalDashboards', 'GoglaDashboards', 'ManageQuantityViewStock',
    'ViewOwnUsers', 'DownloadGlobalAccounts', 'ManageAllAccounts', 'ViewBadgeTransfers',
    'ViewOrphanedPayments', 'FromOrphanedMoveStock', 'ToOrphanedMoveStock',
    'FromWithMeMoveStock', 'ToWithMeMoveStock', 'OrphanedViewStock', 'WithMeViewStock',
    'DeleteMoveStock', 'FromLostMoveStock', 'ToLostMoveStock',
    'ViewOrphanedMessages', 'ViewAllMessages', 'ViewBadgeIssues', 'ViewCreatedLeads',
    'ViewBadgeLeads', 'AddDevices', 'EditSubTypeDevices', 'EditTagsDevices' ,'CreateTagsDevices',
    'AddNotesDevices', 'DeleteNotesDevices', 'DeleteDevices', 'EditWalletPayments',
    'AdjustBalanceAndReconcilePayments', 'AddPayments', 'CreateTagsDevices', 'EditTagsDevices',
    'MakeOnStockOutsideViewActions', 'AddOutgoingMessages', 'ViewOdysseyPayments',
    'OverrideDeliveryDateLimitsLeads', 'FillCustomFormsUserJourney', 'AddPurchasingAddOns', 
    'ConfigureTaskTypeAdmin', 'ViewAssignedTasks', 'AddAssignedTasks', 'EditCreatedTasks', 'DeleteCreatedTasks', 'ChangeStatusOfAssignedTasks',
    'ViewAutomations', 'EditAutomations', 'SyncTaskAssignedToMeMobile', 'PairDevices', 'ConfigurePackageInstallerAdmin', 'ConfigureAutomationsAdmin'
] + all_permissions_in_group('Admin') + \
    all_permissions_in_group('Forms') + \
    all_permissions_in_group('LeadGenerators') + \
    all_permissions_in_group('APIHook') + \
    all_permissions_in_group('Portfolios') + \
    all_permissions_in_group('AddonOffers') + \
    all_permissions_in_group('Offers') + \
    all_permissions_in_group('Roles') + \
    all_permissions_in_group('ClientGroups') + \
    all_permissions_in_group('Regions') + \
    all_permissions_in_group('Accounts') + \
    all_permissions_in_group('Expenses') + \
    all_permissions_in_group('Transfers') + \
    all_permissions_in_group('Logs') + \
    all_permissions_in_group('ReversedPayments') + \
    all_permissions_in_group('APIDocumentation') + \
    all_permissions_in_group('UserJourney') + \
    all_permissions_in_group('Planning')

synthetic_permissions = {
    'EditPhoneNumbers': ['EditClients', 'EditUsers', 'EditLeads', 'AddLeads'],
    'ViewPhoneNumbers': ['ViewClients', 'ViewLeads', 'ViewUsers', 'ViewOrphanedPhoneNumbers'],
    'ViewFormAnswers': ['FillCustomFormsUserJourney', 'ViewClients', 'ViewLeads', 'ViewInteractions'],
    'EditFormAnswers': ['FillCustomFormsUserJourney', 'FillCustomFormsClients', 'FillCustomFormsLeads', 'EditInteractions',
                        'AddInteractions'],
    'AddAddOns': ['EditClients', 'EditLeads'],
    'ViewAddOns': ['ViewClients', 'ViewLeads'],
    'EditExpenses': ['EditOwnExpenses', 'EditOthersExpenses'],
    'AddProduct' : ['AddProductModels']
}

# old: new
renamed_permissions = {
    'AddPaymentManuallyPayments': 'AddPayments',
    'ExportDataSpecial': 'ExportDataAdmin',
    'DoNegativePayCashActions': 'CollectCashNegativeActions',
    'GiveMoreThan2DaysFreeActions': 'GiveDiscountOver2DaysActions',
    'UninstallClients': 'MarkContractDefaultedActions',
    'EditDevices': 'DeleteDevices',
    'ViewInHubStockManagement': 'InStockViewStock',
    'ViewWithMeStockManagement': 'WithMeViewStock',
    'ViewWithClientsStockManagement': 'WithClientsViewStock',
    'ViewOrphanedStockManagement': 'OrphanedViewStock',
    'CreateMovementInHubStockManagement': 'FromInStockMoveStock',
    'CreateOrphanedMovementsStockManagement': 'FromOrphanedMoveStock',
    'CanMakeActionsOutsideViewStockManagement': 'MakeOnStockOutsideViewActions',
    'ConfigureLoanSettingsAdmin': 'ConfigurePaymentManagementAdmin',
    'ViewAllAccounts': 'ViewAccounts',
    'AddShops': 'AddHubs',
    'EditShops': 'EditHubs',
    'DeleteShops': 'DeleteHubs',
    'UsersInHubViewStock': 'WithUsersViewStock',
    'InHubViewStock': 'InStockViewStock',
    'FromInHubMoveStock': 'FromInStockMoveStock',
    'FromUsersInHubMoveStock': 'FromUsersMoveStock',
    'ToInHubMoveStock': 'ToInStockMoveStock',
    'ToUsersInHubMoveStock': 'ToUsersMoveStock',
    'SyncLeads': 'SyncLeadsMobile',
    'SyncCreatedLeads': 'SyncAllCreatedLeadsMobile',
    'SyncGeneratedLeads': 'SyncAllGeneratedLeadsMobile',
    'SyncInstalledLast2WeeksLeads': 'SyncInstalledLast2WeeksLeadsMobile',
    'SyncInstalledLast2MonthsLeads': 'SyncInstalledLast2MonthsLeadsMobile',
    'SyncLeadGenerators': 'SyncLeadGeneratorsMobile',
    'SyncClients': 'SyncClientsMobile',
    'SyncCreatedClients': 'SyncAllCreatedClientsMobile',
    'SyncGeneratedClients': 'SyncAllGeneratedClientsMobile',
    'SyncInteractions': 'SyncInteractionsMobile',
    'SyncPlanning': 'SyncPlanningMobile',
    'SellAddonActions': 'AddToContractAddOns',
    'ConfigureDeviceAPIsAdmin': 'ConfigureDeviceAPIAdmin',
    'MakeActions': 'SyncActivationActions',
    'AddNotesInteractions': 'AddNotesIssues',
    'DeleteNotesInteractions': 'DeleteNotesIssues',
    'DeleteOwnNotesInteractions': 'DeleteOwnNotesIssues',
    'AdjustBalancePayments' : 'AdjustBalanceAndReconcilePayments',
    'MarkAsDeliveredAddOns': 'MarkAsDeliveredAddOns',
    'SyncTaskAssignedToMe': 'SyncTaskAssignedToMeMobile',
}

# When adding new permissions, if they are part of this list,
# they would be given to the current owner of another permission (e.g. 'NewPermission': ['Existing1', 'Existing2'])
associated_permissions = {
    'ListOffers': ['ViewLeads', 'ViewClients'],
    'ViewOffers': ['ViewLeads', 'ViewClients'],
    'AddLeads': ['EditLeads'],
    'ViewCreatedLeads': ['ViewLeads'],
    'SyncLeadsCreatedMobile': ['ViewCreatedLeads'],
    'SyncClientsInClustersMobile': ['ViewClients'],
    'ViewForms': ['ViewSettingsInterfaceAdmin'],
    'AddForms': ['ViewSettingsInterfaceAdmin'],
    'EditForms': ['ViewSettingsInterfaceAdmin'],
    'DeleteForms': ['ViewSettingsInterfaceAdmin'],
    'EditInteractionsSettingsForms': ['ViewSettingsInterfaceAdmin'],
    'EditClientLeadDataSettingsForms': ['ViewSettingsInterfaceAdmin'],
    'AnswerProtectedQuestionForms': ['ViewSettingsInterfaceAdmin'],
    'AdjustBalanceAndReconcilePayments': ['DeletePayments'],
    'GiveNegativeDiscountToCompletedActions': ['DeRegisterActions'],
    'UndoContractDefaultedActions': ['DeRegisterActions'],
    'CancelContractActions': ['DeRegisterActions'],
    'PauseContractActions': ['CancelContractActions'],
    'ResumeContractActions': ['CancelContractActions'],
    'MarkContractDefaultedActions': ['DeRegisterActions'],
    'AddManualMessages': ['ViewSettingsInterfaceAdmin'],
    'ListContracts': ['ListClients'],
    'EditWalletPayments': ['AdjustBalanceAndReconcilePayments'],
    'InStockViewStock': ['ListDevices'],
    'WithMeViewStock': ['ListDevices'],
    'WithClientsViewStock': ['ListDevices'],
    'OrphanedViewStock': ['ListDevices'],
    'FromInStockMoveStock': ['ViewSettingsInterfaceAdmin'],
    'FromOrphanedMoveStock': ['ViewSettingsInterfaceAdmin'],
    'FromUsersMoveStock': ['FromInStockMoveStock'],
    'FromWithMeMoveStock': ['FromInStockMoveStock'],
    'ToInStockMoveStock': ['FromInStockMoveStock'],
    'ToUsersMoveStock': ['FromInStockMoveStock'],
    'ToWithMeMoveStock': ['FromInStockMoveStock'],
    'ToOrphanedMoveStock': ['FromOrphanedMoveStock'],
    'ListAddonOffers': ['ListOffers'],
    'ViewAddonOffers': ['ViewOffers'],
    'AddAddonOffers': ['AddOffers'],
    'AddPurchasingAddOns':['AddAddonOffers'],
    'EditAddonOffers': ['EditOffers'],
    'EditInstalledLeads': ['ApproveLeads'],
    'AddUsers': ['ViewSettingsInterfaceAdmin', 'EditUsers'],
    'CustomizePlatformAdmin': ['EditCustomSMSAdmin'],
    'GiveTokensOfflineActions': ['ApproveLeads'],
    'AddAddOns': ['ConfigurePaymentManagementAdmin', 'AddLeads'],
    'ApproveAddOns': ['ConfigurePaymentManagementAdmin', 'ApproveLeads'],
    'EditPlannedDeliveryDateLeads': ['AddLeads'],
    'ConfigureMobileAppSettingsAdmin': ['EditCustomSMSAdmin'],
    'SyncLeads': ['ViewLeads'],
    'SyncLeadGenerators': ['ViewLeadGenerators'],
    'SyncClients': ['ViewClients'],
    'SyncInteractions': ['ViewInteractions'],
    'SyncPlanning': ['ViewPlanning'],
    'SyncCreatedLeads': ['SyncLeadsCreatedMobile'],
    'SyncCreatedClients': ['SyncLeadsCreatedMobile'],
    'SyncGeneratedLeads': ['SyncLeadsCreatedMobile'],
    'SyncGeneratedClients': ['SyncLeadsCreatedMobile'],
    'SyncCompletedClients': ['SyncCompletedClientsMobile'],
    'SyncInstalledLast2WeeksLeads': ['SyncLeads'],
    'SyncInstalledLast2MonthsLeads': ['SyncLeads'],
    'ConfigureOperationalEntitiesAdmin': ['ConfigureGeneralSettingsAdmin'],
    'AddZones': ['AddHubs'],
    'EditZones': ['EditHubs'],
    'DeleteZones': ['DeleteHubs'],
    'AddRegions': ['AddHubs'],
    'EditRegions': ['EditHubs'],
    'DeleteRegions': ['DeleteHubs'],
    'AddClientGroups': ['AddHubs'],
    'EditClientGroups': ['EditHubs'],
    'DeleteClientGroups': ['DeleteHubs'],
    'EditOfferPartiallyPaidLeads': ['ApproveLeads'],
    'EditOfferAwaitingDeliveryLeads': ['ApproveLeads'],
    'RemoveLastPhoneNumbers': ['EditInstalledLeads'],
    'FillCustomFormsLeads': ['EditLeads'],
    'FillCustomFormsClients': ['EditClients'],
    'EditAllocatedDeviceLeads': ['EditLeads'],
    'ChangeExpectedPaidActions': ['ConfigurePaymentRouterAdmin'],
    'CancelAddOns': ['ApproveAddOns'],
    'OverrideDeliveryDateLimitsLeads': ['ApproveLeads'],
    'MoveToRestrictedStatus': ['ConfigureGeneralSettingsAdmin'],
    'AddTagsClients': ['EditClients'],
    'CreateTagsClients': ['EditClients'],
    'ViewCustomButtonActions':['ViewActions'],
    'MergeClients': ['ConfigureGeneralSettingsAdmin'],
    'ViewOwnLeadGenerators': ['ViewLeadGenerators'],
    'SyncOwnLeadGeneratorMobile': ['SyncLeadGeneratorsMobile'],
    'ListPayments': ['ViewOdysseyPayments'],
    'AddContractTermsChangeAddOns': ['EditLeads', 'EditClients'],
    'EditTagsDevices': ['AddDevices'],
    'CreateTagsDevices': ['AddDevices'],
    'AddNotesDevices': ['AddDevices'],
    'DeleteNotesDevices': ['AddDevices'],
    'AddMoveStock': ['AddDevices'],
    'DeleteMoveStock' : ['AddDevices'],
    'APICallerAdmin': ['ConfigureGeneralSettingsAdmin'],
    'ConfigureProductAdmin': ['ConfigureGeneralSettings'],
    'EditSubTypeDevices': ['ConfigureGeneralSettings'],
    'EditPortfolioLeads': ['EditLeads'],
    'EditPortfolioClients': ['EditClients'],
    'MarkAsDeliveredAddOns': ['EditLeads'],
    'MarkAsDeliveredWithoutPlannedDateAddOns': ['ConfigureGeneralSettingsAdmin'],
    'MarkAsUnDeliveredAddOns': ['ConfigureGeneralSettingsAdmin'],
    'EditPlannedDeliveryDateAddOns': ['ConfigureGeneralSettingsAdmin'],
    'ToLostMoveStock': ['ToOrphanedMoveStock'],
    'FromLostMoveStock': ['FromOrphanedMoveStock'],
    'ViewLumpSumOffers':['ViewOffers'],
    'ViewLoanOffers':['ViewOffers'],
    'EditLoanOffers':['EditOffers'],
    'AddLoanOffers':['AddOffers'],
    'EditRestrictedPersonalDetailsLeads': ['EditLeads'],
    'ConfigureSalesOptionsAdmin': ['ConfigurePersonalInfoAdmin'],
    'ViewPaygoDevices': ['ViewSettingsInterfaceAdmin'],
    'ViewAPIDocumentation': ['CreateAPITokenAdmin'],
    'ViewRoles': ['AssignRoles'],
    'PayClientActions': ['CollectCashActions'],
    'FillCustomFormsUserJourney': ['EditLeads'],
    'RunUserJourney': ['EditLeads'],
    'AddUserJourney': ['CreateAPITokenAdmin'],
    'EditUserJourney': ['CreateAPITokenAdmin'],
    'ListUserJourney': ['CreateAPITokenAdmin'],
    'AddIncomingMessages': ['AddMessages', 'AddManualMessages'],
    'AddTasks': ['ViewSettingsInterfaceAdmin', 'AddPlanning'],
    'EditTasks': ['ViewSettingsInterfaceAdmin', 'EditPlanning'],
    'DeleteTasks': ['ViewSettingsInterfaceAdmin', 'DeletePlanning'],
    'ChangeStatusOfAssignedTasks': ['EditPlanning', 'ViewPlanning'],
    'ViewTasks': ['ViewPlanning'],
    'ViewAssignedTasks': ['ViewPlanning'],
    'AddAssignedTasks': ['ViewPlanning'],
    'EditCreatedTasks': ['ViewPlanning'],
    'DeleteCreatedTasks': ['ViewPlanning'],
    'ConfigureTaskTypeAdmin': ['ViewSettingsInterfaceAdmin'],
    'ViewAutomations': ['ViewSettingsInterfaceAdmin'],
    'EditAutomations': ['ViewSettingsInterfaceAdmin'],
    'SyncTaskAssignedToMeMobile': ['SyncPlanningMobile'],
    'PairDevices': ['DeleteDevices', 'AddDevices'],
    'ConfigurePackageInstallerAdmin': ['ViewSettingsInterfaceAdmin'],
    'ConfigureAutomationsAdmin': ['ViewSettingsInterfaceAdmin'],
}

# same as associated_permissions but directly to roles
associated_roles = {}

metrics_api_permissions = [
    "ViewAutomations",
    "EditUsers",
    "ConfigureGeneralSettingsAdmin",
    "WithMeViewStock",
    "ViewClients",
    "ViewRoles",
    "ViewMessages",
    "WithClientsViewStock",
    "WithUsersViewStock",
    "EditBannerAdmin",
    "ViewUsers",
    "ViewPayments",
    "InStockViewStock",
    "OrphanedViewStock",
    "ViewBillingAdmin"
]

deleted_permissions = [
    'TerminateClients', 'SimulateMPESA', 'MergeLeads', 'EditInstalledLeads', 'DownloadDBBackupAdmin',
    'ListHistoricalData', 'ViewHistoricalData', 'EditHistoricalData', 'DeleteHistoricalData',
    'CreateHistoricalData', 'RunHistoricalData', 'SimulateMPESAAdmin',
    'ViewAllStockManagement', 'ViewInHubStockManagement', 'ViewWithMeStockManagement',
    'ViewWithClientsStockManagement', 'ViewOrphanedStockManagement', 'CreateMovementAllStockManagement',
    'CreateMovementInHubStockManagement', 'CreateOrphanedMovementsStockManagement',
    'CanMakeActionsOutsideViewStockManagement', 'SolveIssues', 'ViewAllUsers', 'ListVillages', 'ViewAllClients',
    'ListClients', 'ListContracts', 'ViewAddOns', 'ListAddOns', 'ListReversedPayments', 'ListUsers', 'ListSurveys'
    'ViewSurveys', 'SyncSurveys', 'ListSurveyAnswers', 'ViewSurveyAnswers', 'AddSurveyAnswers', 'EditSurveyAnswers',
    'CorrectSurveyAnswers', 'SyncSurveyAnswers', 'ViewContracts', 'SyncContracts', 'ViewPhoneNumbers',
    'EditPhoneNumbers', 'ListPhoneNumbers', 'CreatePhoneNumbers', 'ListOffers', 'ViewAllOffers', 'ListAddonOffers'
    'ListPortfolios', 'AllViewStock', 'ViewOrphaned', 'ViewOrphanedDevices', 'ViewAllPayments', 'ViewAllTransfers',
    'SyncClientsInShop', 'SyncClientsInClusters', 'SyncLeadsInShop', 'SyncVillagesInShop', 'SyncVillagesInClusters',
    'ViewAllActions', 'ViewAllExpenses', 'SyncAddonOffers', 'SyncOffers', 'SyncVillages', 'SyncIssues', 'SyncAddOns',
    'SyncCompletedClients', 'SyncVillagesInClustersMobile', 'SyncVillagesInShopMobile', 'AddAddOns', 'SyncLeadsCreatedMobile',
    'SyncLeadsInShopMobile', 'SyncClientsInClustersMobile', 'SyncClientsInShopMobile', 'ViewSurveys',
    'ListSurveys', 'ViewAllActions', 'ListAddonOffers', 'AllMoveStock', 'ViewDevices', 'ListDevices', 'ListClusters',
    'DeletePayments', 'AddNotes', 'DeleteNotes', 'DeleteOwnNotes', 'CollectCashNegativeActions', 'ViewHubs', 'ViewClusters', 'ViewVillages',
    'ConfigureAdvancedSettingsAdmin'
]
