from core_system.operational_entities.services.client_group_getter_service import ClientGroupGetterService
from core_system.operational_entities.services.operational_entities_getter import OperationalEntitiesGetterService
from core_system.users.services.current_user_service import UnauthorizedUser
from datetime import datetime, timedelta
from sales_system.leads.models.status_category import StatusCategory
from shared.services.base_getter_service import BaseGetterService
from pony import orm
from sales_system.leads.models.lead import Lead
from core_system.core_entities import db
from config import ENV_VAR
from shared.helpers.db_helpers import searchable_text
from tests.support.mock_query import MockQuery


class LeadGetterService(BaseGetterService):

    OBJ_NAME = 'Lead'

    @classmethod
    def get_from_user_and_id(cls, user, id, strict=False, main_resource=False, **kwargs):
        if id and int(id) > 2147483647:
            # This is to avoid sending error to monitoring when people enter numbers above max int
            # It is quite common in some distributors (pasting twice the same lead ID)
            return
        lead = Lead.get(id=id)
        if not lead or isinstance(user, UnauthorizedUser):
            return cls.raise_strict(main_resource, **kwargs) if strict else None

        # Use ids for robust comparison even if user / reporter are different proxy instances.
        user_id = getattr(user, 'id', None)

        # Check "created/generated by me" first so ViewCreatedLeads-only users don't depend on ViewLeads.
        if user.can_access_in_any('ViewCreatedLeads') or user.can_access_in_any('SyncAllCreatedLeadsMobile'):
            if lead.reporter and getattr(lead.reporter, 'id', None) == user_id:
                return lead
        if user.can_access_in_any('SyncAllGeneratedLeadsMobile'):
            lead_generator_person = getattr(getattr(lead, 'generator', None), 'person', None)
            if lead_generator_person and getattr(lead_generator_person, 'id', None) == getattr(getattr(user, 'person', None), 'id', None):
                return lead
        # Entity-based access: only ViewLeads grants access to any lead in the entity.
        entities = [r.entity for r in user.get_roles_in_entities_for_permission('ViewLeads')]
        if None in entities:
            return lead  # can access all
        if lead.person.client_group in entities:
            return lead
        if lead.person.village in entities:
            return lead
        for ancestor in lead.person.village.all_ancestors:
            if ancestor in entities:
                return lead
        return cls.raise_strict(main_resource, **kwargs) if strict else None
        
    @classmethod
    def preprocess_list_filters(cls, user, **kwargs):
        kwargs['client_group'] = ClientGroupGetterService.extract_from_user_and_id(user, kwargs, 'client_group_id')
        return kwargs

    @classmethod
    def get_from_filtered_view(cls, user, view=None, entity=None, portfolio=None, client_group=None, search=None, generated_by=None, contract_offer=None, offer_type=None, from_delivery_date=None, to_delivery_date=None):

        extra = {}
        if view == 'managed_by_me':
            extra['managed_by'] = user
        elif view == 'generated_by_me':
            generated_by = user

        leads = cls.get_list(
            user,
            entity=entity,
            portfolio=portfolio,
            search=search,
            client_group=client_group,
            generated_by=generated_by,
            contract_offer=contract_offer,
            offer_type=offer_type,
            from_delivery_date=from_delivery_date,
            to_delivery_date=to_delivery_date,
            **extra
        )
        return leads

    @classmethod
    def get_leads_with_permission(cls, current_user, permission, for_sync=False, managed_by=None, extra_ids=[]):
        if for_sync or managed_by or not current_user.can_access_in_all(permission):
            villages_id, client_groups_ids = current_user.get_villages_and_client_groups_with_permission(permission, for_sync=for_sync, managed_by=managed_by, return_villages_ids=True)
            if client_groups_ids:
                if not extra_ids:
                    return orm.select(l for l in Lead if l.person.village.id in villages_id or l.person.client_group.id in client_groups_ids)
                else:
                    return orm.select(l for l in Lead if l.id in extra_ids or l.person.village.id in villages_id or l.person.client_group.id in client_groups_ids)
            else:
                if not extra_ids:
                    return orm.select(l for l in Lead if l.person.village.id in villages_id)
                else:
                    return orm.select(l for l in Lead if l.id in extra_ids or l.person.village.id in villages_id)
        else:
            return Lead.select()

    @classmethod
    def get_filtered_objects(cls, current_user, installed=None, created_by=None, entity=None, portfolio=None, search=None, client_group=None, managed_by=None,
                        generated_by=None, lead_id=None, contract_reference='', status_category='', status=None, status_id=None, entity_id=None, from_planned_delivery_date=None, 
                        to_planned_delivery_date=None, custom_id=None, contract_offer=None, offer_type=None, from_status_change_date=None, to_status_change_date=None, phone_number=None, from_delivery_date=None, to_delivery_date=None, unique_person=False, **kwargs):
        if isinstance(current_user, UnauthorizedUser):
            return Lead.select(lambda l: l.id == -1)
        current_user = current_user.reload()
        if lead_id:
            lead = cls.get_from_user_and_id(current_user, lead_id)
            leads = Lead.select(lambda l: l.id == lead.id)
        elif current_user.can_access_in_all('ViewLeads'):
            # No need to check created if can view all
            leads = Lead.select()
            if managed_by:
                leads_in_groups = leads.filter(lambda l: l.person.client_group.user_in_charge == managed_by)
                leads = leads.filter(lambda l: 
                    l in leads_in_groups or (not l.person.client_group and l.person.village in OperationalEntitiesGetterService.managed_by(managed_by, level=0))
                )
        else:
            created_leads_ids = []
            generated_leads_ids = []
            if current_user.can_access_in_any('ViewCreatedLeads') or current_user.can_access_in_any('SyncAllCreatedLeadsMobile'):
                created_leads_ids = orm.select(l.id for l in Lead if l.reporter == current_user)[:]
            if current_user.can_access_in_any('SyncAllGeneratedLeadsMobile'):
                generated_leads_ids = orm.select(l.id for l in Lead if l.generator.person == current_user.person)[:]
            extra_ids = created_leads_ids + generated_leads_ids
            leads = cls.get_leads_with_permission(current_user, 'ViewLeads', managed_by=managed_by, extra_ids=extra_ids)
        if installed is not None:
            leads = leads.filter(lambda l: l.installed == installed)
        if created_by:
            leads = leads.filter(lambda l: l.reporter == created_by)
        if generated_by:
            leads = leads.filter(lambda l: generated_by.person.leadGenerator == l.generator)
        if entity_id:
            entity = OperationalEntitiesGetterService.get_from_user_and_id(current_user, entity_id)
            if not entity:
                return leads.filter(lambda l: l.id == -1)
        if entity:
            leads = leads.filter(lambda l: l.person.village in entity.descendants)
        if portfolio:
            leads = leads.filter(lambda l: l.portfolio == portfolio)
        if search:
            from core_system.phone_numbers.services.phone_number_getter import PhoneNumberGetterService
            persons = PhoneNumberGetterService.find_persons_if_search_is_number(search)
            if search.isdigit():
                search_int = int(search)
                exact_leads_ids = orm.select(e.id for e in leads if e.id == search_int or e.person.custom_id == search or e.person in persons)[:]
            else:
                exact_leads_ids = orm.select(e.id for e in leads if e.person.custom_id == search or e.person in persons)[:]
            search = searchable_text(search)
            search_leads_ids = orm.select(e.id for e in leads if search in e.person.searchable_name)
            leads = Lead.select(lambda e: e.id in exact_leads_ids+search_leads_ids)
        if client_group:
            leads = leads.filter(lambda l: l.person.client_group == client_group)
        if phone_number:
            from core_system.phone_numbers.services.phone_number_getter import \
                PhoneNumberGetterService
            persons = PhoneNumberGetterService.find_persons_if_search_is_number(phone_number)
            leads = leads.filter(lambda c: c.person in persons)
        if contract_reference:
            leads = leads.filter(lambda l: l.future_contract_reference == contract_reference)
        if status_category:
            # Handle both single value (string) and multiple values (list)
            if isinstance(status_category, list):
                status_categories = [getattr(StatusCategory, cat) for cat in status_category if hasattr(StatusCategory, cat)]
                if status_categories:
                    leads = leads.filter(lambda l: l.status.category in status_categories)
            else:
                leads = leads.filter(lambda l: l.status.category == getattr(StatusCategory, status_category))
        if status:
            print(f'hello kelvin this is the status: {status}')
            # Handle both single value (string) and multiple values (list)
            if isinstance(status, list):
                if status:
                    leads = leads.filter(lambda l: l.status.name in status)
            else:
                leads = leads.filter(lambda l: l.status.name == status)
        if status_id:
            # Handle both single value (int) and multiple values (list)
            if isinstance(status_id, list):
                if status_id:
                    leads = leads.filter(lambda l: l.status.id in status_id)
            else:
                leads = leads.filter(lambda l: l.status.id == status_id)
        if from_planned_delivery_date:
            leads = leads.filter(lambda l: l.agreedDeliveryDate >= from_planned_delivery_date)
        if to_planned_delivery_date:
            leads = leads.filter(lambda l: l.agreedDeliveryDate < to_planned_delivery_date)
        if from_status_change_date:
            leads = leads.filter(lambda l: l.statusUpdate >= from_status_change_date)
        if to_status_change_date:
            leads = leads.filter(lambda l: l.statusUpdate < to_status_change_date)
        if custom_id:
            leads = leads.filter(lambda l: l.person.custom_id == custom_id)
        if contract_offer:
            leads = leads.filter(lambda l: l.offer == contract_offer)
        if offer_type:
            leads = leads.filter(lambda l: l.offer.type == offer_type)
        if from_delivery_date and to_delivery_date:
            leads = leads.filter(lambda l: (l.agreedDeliveryDate >= from_delivery_date and l.agreedDeliveryDate <= to_delivery_date) or orm.exists(l.addons.filter(lambda a: a.delivery_date >= from_delivery_date and a.delivery_date <= to_delivery_date)))
        elif from_delivery_date:
            leads = leads.filter(lambda l: l.agreedDeliveryDate >= from_delivery_date or orm.exists(l.addons.filter(lambda a: a.delivery_date >= from_delivery_date)))
        elif to_delivery_date:
            leads = leads.filter(lambda l: l.agreedDeliveryDate <= to_delivery_date or orm.exists(l.addons.filter(lambda a: a.delivery_date <= to_delivery_date)))
        elif unique_person:
            unique_person_lead_ids_sql = """WITH all_leads AS (
                                                SELECT  id,
                                                        ROW_NUMBER() OVER (PARTITION BY person) AS row_number
                                                FROM
                                                lead
                                            )
                                            SELECT  id
                                            FROM    all_leads
                                            WHERE row_number = 1

            """
            leads = leads.filter(lambda l: l.id in orm.raw_sql(unique_person_lead_ids_sql))
        return leads

    @classmethod
    def get_lead_by_mobile_uuid_for_user(cls, mobile_uuid, user):
        all_leads = cls.get_list(user)
        try:
            return all_leads.filter(lambda lead: lead.mobile_uuid == mobile_uuid).first()
        except Exception as e:
            return None

    @classmethod
    def get_list_for_mobile(cls, user, cached_ids=None, **kwargs):
        generated_leads = []
        created_leads = []
        leads = orm.select(l.id for l in cls.get_leads_with_permission(user, 'SyncLeadsMobile', for_sync=True))[:]
        if user.can_access('SyncAllGeneratedLeadsMobile'):
            generated_leads = orm.select(l.id for l in cls.get_leads_generated_by_user(user))[:]
        if user.can_access('SyncAllCreatedLeadsMobile'):
            created_leads = orm.select(l.id for l in cls.get_leads_created_by(user))[:]
        leads = orm.select(l for l in Lead if l.id in leads+generated_leads+created_leads)

        date_15_days = datetime.today() - timedelta(days=15)
        date_60_days = datetime.today() - timedelta(days=60)
        date_365_days = datetime.today() - timedelta(days=365)
        installed_last_12_months_villages = [v.id for v in user.get_entities_with_permission('SyncInstalledLast12MonthsLeadsMobile', level=0, for_sync=True)]
        installedInLast12months = orm.select(l.id for l in leads if l.person.village.id in installed_last_12_months_villages
                                            and l.installed and l.contract and l.contract.start_time >= date_365_days)[:]
        installed_last_2_months_villages = [v.id for v in user.get_entities_with_permission('SyncInstalledLast2MonthsLeadsMobile', level=0, for_sync=True)]
        installedInLast2months = orm.select(l.id for l in leads if l.person.village.id in installed_last_2_months_villages
                                            and l.installed and l.contract and l.contract.start_time >= date_60_days)[:]
        installed_last_2_weeks_villages = [v.id for v in user.get_entities_with_permission('SyncInstalledLast2WeeksLeadsMobile', level=0, for_sync=True)]
        installedInLast2weeks = orm.select(l.id for l in leads if l.person.village.id in installed_last_2_weeks_villages 
                                            and l.installed and l.contract and l.contract.start_time >= date_15_days)[:]
        leads = leads.filter(lambda l: (not l.installed and not l.discarded)
                                or l.id in installedInLast12months+installedInLast2months+installedInLast2weeks)
        return leads

    @classmethod
    def get_leads_ready_for_payment(cls):
        return orm.select(lead for lead in Lead if lead.can_receive_payment)

    @classmethod
    def get_leads_created_by(cls, user):
        if not isinstance(user, db.User):
            return Lead.select(lambda l: l.id == -1)
        return cls.get_list(user, created_by=user)
        # return Lead.select(lambda l: l.reporter == user)

    @classmethod
    def get_leads_in_user_shop(cls, user):
        if not isinstance(user, db.User) and ENV_VAR == 'TEST':
            return Lead.select()
        return Lead.select(lambda l: l.person.village.parent.parent == user.shop)

    @classmethod
    def get_leads_generated_by_user(cls, user):
        if not isinstance(user, db.User) and ENV_VAR == 'TEST':
            return Lead.select()
        return Lead.select(lambda l: l.generator.person == user.person)

    @classmethod
    def get_leads_in_shop(cls, shop):
        return Lead.select(lambda l: l.person.village.parent.parent == shop)

    @classmethod
    def get_leads_in_user_cluster(cls, user):
        return Lead.select(lambda l: (not l.person.client_group and l.person.village.parent.user_in_charge == user) or l.person.client_group.user_in_charge == user)

    @classmethod
    def get_lead_for_communication_tool(cls, filters, user):
        intl = lambda l: [int(i) for i in l]
        locations = filters.get('Location', [])
        statuses = filters.get('Status', [])
        offer_types = filters.get('OfferType', [])

        if not locations or not statuses:
            leads = MockQuery([])
        else:
            leads = cls.get_list(user)
            leads = leads.filter(lambda l: l.status.category != StatusCategory.installed)
            if not 'all' in locations:
                leads = leads.filter(lambda lead: lead.person.village.parent.parent.id in intl(locations))
            if not 'all' in statuses:
                leads = leads.filter(lambda lead: lead.status.id in intl(statuses))
            if not 'all' in offer_types:
                leads_offer = leads.filter(lambda lead: lead.offer.type in offer_types)
                if 'none' in offer_types:
                    leads = leads.filter(lambda lead: lead in leads_offer or not lead.offer)
                else:
                    leads = leads_offer
        return leads