from payg_loan_system.offers.models import LoanOffer, LumpSumOffer, Offer, OfferType, TimeBasedOffer
from pony import orm


@orm.db_session
def create_offers():
    this_offer = LoanOffer(
        id=888,
        name='Test Offer General',
        code='TOG',
        family='Home',
        in_use=True,
        in_use_for_new_clients=True,
        registration_fee=100000,
        time_to_ownership_in_days=7 * 100,
        free_credit_at_start=7,
        no_approval_required=False,
        device_type='NPG',
        unit_cost=200000,
        lighting_global_compliant=False,
        base_price_amount=1000,
        base_price_credit=7,
        discount_price_1_amount=2000,
        discount_price_1_credit=15,
        panel_size_in_w=10,
        battery_size_in_ah=5,
    )

    this_offer_2 = LoanOffer(
        id=889,
        name='Test Offer General 2',
        code='TOG2',
        family='Home',
        in_use=True,
        in_use_for_new_clients=True,
        registration_fee=50000,
        time_to_ownership_in_days=7 * 100,
        free_credit_at_start=7,
        no_approval_required=True,
        device_type='NPG',
        unit_cost=200000,
        lighting_global_compliant=False,
        base_price_amount=1000,
        base_price_credit=7,
        discount_price_1_amount=4000,
        discount_price_1_credit=30,
        panel_size_in_w=10,
        battery_size_in_ah=5,
    )

    this_offer_3 = LoanOffer(
        id=890,
        name='Test Offer General 3',
        code='TOG3',
        family='Home',
        in_use=True,
        in_use_for_new_clients=True,
        registration_fee=50000,
        time_to_ownership_in_days=7 * 100,
        free_credit_at_start=7,
        no_approval_required=True,
        device_type='NPG',
        unit_cost=200000,
        lighting_global_compliant=False,
        base_price_amount=1000,
        base_price_credit=7,
        discount_price_1_amount=4000,
        discount_price_1_credit=30,
        panel_size_in_w=10,
        battery_size_in_ah=5,
    )

    this_offer_4 = LoanOffer(
        id=891,
        name='Test Offer General 4',
        code='TOG4',
        family='Home',
        in_use=True,
        in_use_for_new_clients=True,
        registration_fee=100000,
        time_to_ownership_in_days=7 * 100,
        free_credit_at_start=7,
        no_approval_required=True,
        device_type='NPG',
        unit_cost=200000,
        lighting_global_compliant=False,
        base_price_amount=1000,
        base_price_credit=7,
        discount_price_1_amount=4000,
        discount_price_1_credit=30,
        panel_size_in_w=10,
        battery_size_in_ah=5,
    )

    this_offer_5 = LoanOffer(
        id=892,
        name='Test Offer General 5',
        code='TOG5',
        family='Home',
        in_use=True,
        in_use_for_new_clients=True,
        registration_fee=100000,
        time_to_ownership_in_days=7 * 100,
        free_credit_at_start=7,
        no_approval_required=True,
        device_type='NPG',
        unit_cost=200000,
        lighting_global_compliant=False,
        base_price_amount=1500,
        base_price_credit=7,
        discount_price_1_amount=6000,
        discount_price_1_credit=30,
        panel_size_in_w=10,
        battery_size_in_ah=5,
    )

    this_offer_6 = LoanOffer(
        id=893,
        name='Test Offer General 6',
        code='TOG6',
        family='Home',
        in_use=True,
        in_use_for_new_clients=True,
        registration_fee=1.5,
        time_to_ownership_in_days=7 * 100,
        free_credit_at_start=7,
        no_approval_required=True,
        device_type='NPG',
        unit_cost=125.5,
        lighting_global_compliant=False,
        base_price_amount=2.5,
        base_price_credit=7,
        discount_price_1_amount=10,
        discount_price_1_credit=7 * 5,
        panel_size_in_w=10,
        battery_size_in_ah=5,
    )
    
    this_offer_7 = LumpSumOffer(
        id=894,
        name='Test Offer General 7',
        code='TOG7',
        family='Home',
        in_use=True,
        in_use_for_new_clients=True,
        registration_fee=1000,
        free_credit_at_start=1,
        no_approval_required=True,
        device_type='NPG',
        unit_cost=125.5,
        lighting_global_compliant=False,
        base_price_amount=2.5,
        base_price_credit=1,
        panel_size_in_w=10,
        battery_size_in_ah=5,
    )
    
    this_offer_8 = TimeBasedOffer(
        id=895,
        name='Test Offer General 8',
        code='TOG8',
        family='Home',
        in_use=True,
        in_use_for_new_clients=True,
        registration_fee=1.5,
        free_credit_at_start=7,
        no_approval_required=True,
        device_type='NPG',
        unit_cost=125.5,
        lighting_global_compliant=False,
        base_price_amount=2.5,
        base_price_credit=7,
        discount_price_1_amount=10,
        discount_price_1_credit=7 * 5,
        panel_size_in_w=10,
        battery_size_in_ah=5,
    )
